# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 02:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('before_value', models.CharField(max_length=30)),
                ('after_value', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_ground_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, default=uuid.uuid4, max_length=64)),
                ('country_name', models.CharField(max_length=64)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(default=uuid.uuid4, max_length=64, null=True)),
                ('section_name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=True)),
                ('fk_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.Country')),
                ('fk_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type_code', models.CharField(default=uuid.uuid4, max_length=64, null=True)),
                ('section_type_name', models.CharField(max_length=40, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='fk_section_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='country.SectionType'),
        ),
    ]
