# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-31 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=30)),
                ('table', models.CharField(db_index=True, max_length=20)),
                ('field', models.CharField(db_index=True, max_length=20)),
                ('before_value', models.CharField(db_index=True, max_length=30)),
                ('after_value', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_country_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=64)),
                ('country_name', models.CharField(max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, null=True)),
                ('section_name', models.CharField(max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('fk_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_country', to='country.Country')),
                ('fk_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_section', to='country.Section')),
            ],
        ),
        migrations.CreateModel(
            name='SectionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_type_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64, null=True)),
                ('section_type_name', models.CharField(max_length=40, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='sectiontype',
            index_together=set([('section_type_code', 'active')]),
        ),
        migrations.AddField(
            model_name='section',
            name='fk_section_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_section_type', to='country.SectionType'),
        ),
        migrations.AlterIndexTogether(
            name='country',
            index_together=set([('country_code', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='section',
            index_together=set([('section_code', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='auditorcountry',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
    ]
