# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 02:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorcountry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_country_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
