# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-27 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorcountry',
            name='object_id',
            field=models.IntegerField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='action',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='after_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='before_value',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='field',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='table',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterIndexTogether(
            name='auditorcountry',
            index_together=set([('action', 'table', 'object_id', 'user')]),
        ),
    ]
