# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_auto_20170323_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='fk_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_country', to='country.Country'),
        ),
        migrations.AlterField(
            model_name='section',
            name='fk_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_section', to='country.Section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='fk_section_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_section_type', to='country.SectionType'),
        ),
    ]
