# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20170323_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_code',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='sectiontype',
            name='section_type_code',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64, null=True),
        ),
    ]
