# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-27 16:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_country_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorcountry',
            name='after_value',
            field=models.CharField(max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='before_value',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
