# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-27 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20170827_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorcountry',
            name='after_value',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='before_value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
