# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-26 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20170323_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='fk_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section_section', to='country.Section'),
        ),
    ]
