# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20170326_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorcountry',
            name='action',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='after_value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='before_value',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='field',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditorcountry',
            name='table',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='country',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='sectiontype',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterIndexTogether(
            name='auditorcountry',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='country',
            index_together=set([('country_code', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='section',
            index_together=set([('section_code', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='sectiontype',
            index_together=set([('section_type_code', 'active')]),
        ),
    ]
