# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-01 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0006_auto_20170827_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='version',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sectiontype',
            name='version',
            field=models.IntegerField(null=True),
        ),
    ]
