# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-26 04:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('before_value', models.CharField(max_length=30)),
                ('after_value', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('fk_sign_activity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SignUpActivities')),
            ],
        ),
    ]
