# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-31 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditorProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=30)),
                ('table', models.CharField(db_index=True, max_length=100)),
                ('field', models.CharField(db_index=True, max_length=100)),
                ('before_value', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('after_value', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('date', models.DateField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_profile_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('fk_sign_activity_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SignUpActivities')),
            ],
        ),
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('description', models.CharField(max_length=30, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('document_id', models.IntegerField(db_index=True, max_length=11)),
                ('first_name', models.CharField(db_index=True, max_length=20)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('mobil_number', models.CharField(blank=True, max_length=11, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField(default=0, null=True)),
                ('fk_id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.IdType')),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='idtype',
            index_together=set([('id_type_code', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='profile',
            index_together=set([('active', 'fk_user'), ('profile_code', 'active'), ('document_id', 'active', 'fk_user')]),
        ),
        migrations.AlterIndexTogether(
            name='auditorprofile',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
    ]
