# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-13 20:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('document_id', models.IntegerField(db_index=True, max_length=11)),
                ('first_name', models.CharField(db_index=True, max_length=20)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('movil_number', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, db_index=True, max_length=70, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('fk_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='action',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='after_value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='before_value',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='field',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='table',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterIndexTogether(
            name='auditorprofile',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='profile',
            index_together=set([('profile_code', 'active'), ('document_id', 'active', 'fk_user')]),
        ),
    ]
