# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-05 02:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170413_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('description', models.CharField(max_length=30, null=True)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='fk_id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.IdType'),
            preserve_default=False,
        ),
        migrations.AlterIndexTogether(
            name='profile',
            index_together=set([('active', 'fk_user'), ('profile_code', 'active'), ('document_id', 'active', 'fk_user')]),
        ),
        migrations.AlterIndexTogether(
            name='idtype',
            index_together=set([('id_type_code', 'active')]),
        ),
    ]
