# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-01 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170801_0924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorprofile',
            name='after_value',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='before_value',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
