# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2018-01-08 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170801_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
