# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20170504_2136'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='before_value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
    ]
