# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-21 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20170507_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='movil_number',
        ),
        migrations.AddField(
            model_name='profile',
            name='mobil_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='version',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
