# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-29 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20170521_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
