# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-29 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170529_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorprofile',
            name='field',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='auditorprofile',
            name='table',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
