# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-24 03:05
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_code',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64),
        ),
    ]
