# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20170323_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
