# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-07-31 22:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('begin_date', models.DateField(db_index=True)),
                ('finish_date', models.DateField(db_index=True)),
                ('topic', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('limit', models.IntegerField(blank=True, null=True)),
                ('is_pay', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_type_Code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('description', models.CharField(max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditorActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=30)),
                ('table', models.CharField(db_index=True, max_length=20)),
                ('field', models.CharField(db_index=True, max_length=20)),
                ('before_value', models.CharField(db_index=True, max_length=120)),
                ('after_value', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_activities_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('count', models.IntegerField(blank=True, null=True)),
                ('fk_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterIndexTogether(
            name='activitiestype',
            index_together=set([('activities_type_Code', 'active')]),
        ),
        migrations.AddField(
            model_name='activities',
            name='fk_activities_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.ActivitiesType'),
        ),
        migrations.AddField(
            model_name='activities',
            name='fk_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Section'),
        ),
        migrations.AlterIndexTogether(
            name='signupactivities',
            index_together=set([('sign_up_code', 'active'), ('active', 'count')]),
        ),
        migrations.AlterIndexTogether(
            name='auditoractivity',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='activities',
            index_together=set([('activities_code', 'finish_date', 'active'), ('activities_code', 'begin_date', 'active', 'is_pay'), ('activities_code', 'finish_date', 'active', 'limit')]),
        ),
    ]
