# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-26 04:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('country', '0004_auto_20170323_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('begin_date', models.DateField()),
                ('finish_date', models.DateField()),
                ('topic', models.CharField(max_length=200)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('isPaid', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ActivitiesType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activities_type_Code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('description', models.CharField(max_length=30)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditorTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('before_value', models.CharField(max_length=30)),
                ('after_value', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_activities_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpActivities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('fk_activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
                ('fk_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='fk_activities_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.ActivitiesType'),
        ),
        migrations.AddField(
            model_name='activities',
            name='fk_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.Country'),
        ),
    ]
