# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-10-08 01:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='topic',
            new_name='pre_description',
        ),
        migrations.AddField(
            model_name='activities',
            name='image_location',
            field=models.ImageField(default=datetime.datetime(2017, 10, 7, 20, 0, 16, 891000), upload_to='activity_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='activities',
            name='image_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='activities',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activities',
            name='title',
            field=models.CharField(default=datetime.datetime(2017, 10, 7, 20, 0, 27, 529000), max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activities',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
