# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-30 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='activities',
            index_together=set([('activities_code', 'begin_date', 'active', 'isPaid')]),
        ),
    ]
