# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20170329_2220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activities',
            old_name='isPaid',
            new_name='is_pay',
        ),
        migrations.AlterField(
            model_name='activities',
            name='begin_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='activities',
            name='finish_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='action',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='after_value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='before_value',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='field',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='table',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='signupactivities',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterIndexTogether(
            name='activities',
            index_together=set([('activities_code', 'finish_date', 'active'), ('activities_code', 'begin_date', 'active', 'is_pay')]),
        ),
        migrations.AlterIndexTogether(
            name='activitiestype',
            index_together=set([('activities_type_Code', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='auditortopic',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='signupactivities',
            index_together=set([('sign_up_code', 'active')]),
        ),
    ]
