# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-05 03:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20170404_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='description',
            field=models.CharField(default=datetime.datetime(2017, 4, 5, 3, 10, 29, 272000, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
