# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-13 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_activities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditortopic',
            name='after_value',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='before_value',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='auditortopic',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
