# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-13 20:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20170413_1513'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuditorTopic',
            new_name='AuditorActivity',
        ),
    ]
