# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-05-05 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20170413_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='activities',
            name='limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='signupactivities',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterIndexTogether(
            name='activities',
            index_together=set([('activities_code', 'finish_date', 'active'), ('activities_code', 'begin_date', 'active', 'is_pay'), ('activities_code', 'finish_date', 'active', 'limit')]),
        ),
        migrations.AlterIndexTogether(
            name='signupactivities',
            index_together=set([('sign_up_code', 'active'), ('active', 'count')]),
        ),
    ]
