# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-27 00:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topics', '0001_initial'),
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agenda_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('schedule', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditorAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('before_value', models.CharField(max_length=30)),
                ('after_value', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_agenda_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SignUpSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_up_schedule_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('count', models.CharField(max_length=2000)),
                ('action', models.BooleanField(default=True)),
                ('fk_sign_up_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.SignUpActivities')),
            ],
        ),
        migrations.CreateModel(
            name='TopicAgenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_agenda_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('fk_activity_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.ActivityRoom')),
                ('fk_agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.Agenda')),
            ],
        ),
        migrations.AddField(
            model_name='signupschedule',
            name='fk_topic_agenda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agenda.TopicAgenda'),
        ),
    ]
