# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-31 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicagenda',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='topicagenda',
            name='topic_agenda_code',
            field=models.CharField(default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterIndexTogether(
            name='topicagenda',
            index_together=set([('topic_agenda_code', 'active')]),
        ),
    ]
