# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-04-05 02:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_auto_20170330_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoragenda',
            name='action',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoragenda',
            name='after_value',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='auditoragenda',
            name='before_value',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='auditoragenda',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='auditoragenda',
            name='field',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='auditoragenda',
            name='table',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='signupschedule',
            name='action',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='topicagenda',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='topicagenda',
            name='topic_agenda_code',
            field=models.CharField(db_index=True, default=uuid.uuid4, max_length=64),
        ),
        migrations.AlterIndexTogether(
            name='agenda',
            index_together=set([('agenda_code', 'date', 'active')]),
        ),
        migrations.AlterIndexTogether(
            name='auditoragenda',
            index_together=set([('action', 'table', 'field', 'before_value', 'after_value', 'date')]),
        ),
        migrations.AlterIndexTogether(
            name='signupschedule',
            index_together=set([('sign_up_schedule_code', 'action')]),
        ),
    ]
