# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-26 04:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activities', '0001_initial'),
        ('rooms', '0002_auto_20170323_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_room_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(default=True)),
                ('fk_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Activities')),
                ('fk_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
        ),
        migrations.CreateModel(
            name='AuditorTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=30)),
                ('table', models.CharField(max_length=20)),
                ('field', models.CharField(max_length=20)),
                ('before_value', models.CharField(max_length=30)),
                ('after_value', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditor_topic_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_code', models.CharField(db_index=True, default=uuid.uuid4, max_length=64)),
                ('topic_name', models.CharField(blank=True, max_length=40, null=True)),
                ('professor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='activityroom',
            name='fk_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='topics.Topic'),
        ),
    ]
