# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-03-26 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityroom',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
