# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2017-08-01 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRolActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfileRolActivity', models.CharField(blank=True, db_index=True, default=uuid.uuid4, max_length=64)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('version', models.IntegerField()),
                ('fk_activity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_profile_activity', to='activities.Activities')),
                ('fk_rol_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles_profile_activity', to='roles.RolesProfile')),
            ],
        ),
    ]
